### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attributes')

### ISSUE THREAD

**Issue by GerdRuetten** [ibBogdan/lovelace-htc-flipclock-weather#23]
Hi Bogdan,

first, thank you very much for your work!

After integration  your card, i get following JS-errors:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attributes')
    at HtcWeather.render (htc-flipclock-weather.js?v1.3.0:195:40)
    at HtcWeather.shouldUpdate (htc-flipclock-weather.js?v1.3.0:167:18)
    at HtcWeather.performUpdate (updating-element.js?module:473:14)
    at HtcWeather._enqueueUpdate (updating-element.js?module:437:25)

```
and the card is not show on the lovelance-Dashboard.

I control the integration many times.
I clear the browser-cache.

What should i do?

Can you help me please

Thank you!

Best regards!
Gerd

**Comment by GerdRuetten** [comment]
> hmm.. check you forecast plugin. seems to be an error there. what are you using to get the weather?

I use this HACS-Integration: https://github.com/FL550/dwd_weather

Should i test a second forcecast-Integration?

**Comment by GerdRuetten** [comment]
I'm sooooooooo stupid!

Your question whitch forecast plugin i use, had open my eyes.

I copy your example markdow-Code:

```
type: custom:htc-weather-card
entity: weather.dark_sky
sun: sun.sun
high_low_entity:
  entity_id: sensor.time_utc
  name: UTC Time

```
But my entitie named

```
type: custom:htc-weather-card
entity: weather.dwd_weather_bedburg_weiler_hohen
sun: sun.sun
high_low_entity:
  entity_id: sensor.time_utc
  name: UTC Time

```

And now ... your flipclock-weather Card works perfectly

Sorry for my stupid!
